fix : city page fix
Lebanon-WBC-Capstones/discover-the-north-web pull request #103
Opened 2021-03-01 09:58 UTC by hiba28

2021-03-01 10:11 UTC, osamaakb requested changes

2021-03-01 10:11 UTC, osamaakb commented on src/Pages/CitiesPage/CitiesPage.js
> +import CITIES from '../../MockData/cities.json';
this should be small case
```suggestion
import cities from '../../MockData/cities.json';
```

2021-03-01 10:11 UTC, osamaakb commented
can I get more info about this PR?

2021-03-01 17:59 UTC, hiba28 commented
Since we changed the city card design so sat the page design as grid view

2021-03-02 06:53 UTC, osamaakb commented
ok, can you please just change the `CITIES` to `cities` then

2021-03-03 15:11 UTC, osamaakb approved these changes

2021-03-03 15:11 UTC, osamaakb approved these changes

2021-03-03 15:11 UTC, merged