Feat: design
Lebanon-WBC-Capstones/discover-the-north-web pull request #11
Opened 2021-02-11 21:08 UTC by MaryamAK7

2021-02-11 21:34 UTC, osamaakb requested changes
Thanks Maryam for the work, I will review again once changes are made (:

2021-02-11 21:34 UTC, osamaakb commented on src/App.css
> +@import '~antd/dist/antd.css';
how did you import this since Hibar still didn't, please can you remove it for now till hiba add it

2021-02-11 21:34 UTC, osamaakb commented on src/Components/Search/Search.js
> +import { SearchOutlined} from '@ant-design/icons';
same here for ant

2021-02-11 21:34 UTC, osamaakb commented on package.json
> -  "devDependencies": {
can I know why did you remove these?

2021-02-11 21:34 UTC, osamaakb commented on package.json
> +    "web-vitals": "^1.1.0"
why did you update this web-vitals version?

2021-02-11 21:34 UTC, osamaakb commented on package.json
> +    "@ant-design/icons": "^4.5.0",
I like that you trying to implement this but this is @hiba28  task for now

2021-02-11 21:45 UTC, MaryamAK7 commented
Thanks, I couldn't do my task without installing and importing ant (so it modified the package.json file). Didn't you tell us to import all the files even the package.json one? Wouldn't it cause an error if I just push the component file?🤔

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: osamaakb <notifications@github.com>
Sent: Thursday, February 11, 2021 11:34:51 PM
To: Lebanon-WBC-Capstones/discover-the-north-web <discover-the-north-web@noreply.github.com>
Cc: MaryamAK7 <Maryam.abdelkarim@hotmail.com>; State change <state_change@noreply.github.com>
Subject: Re: [Lebanon-WBC-Capstones/discover-the-north-web] Feat: design (#11)


@osamaakb requested changes on this pull request.

Thanks Maryam for the work, I will review again once changes are made (:

________________________________

In src/App.css<https://github.com/Lebanon-WBC-Capstones/discover-the-north-web/pull/11#discussion_r574841004>:

> @@ -1,3 +1,4 @@
+@import '~antd/dist/antd.css';


how did you import this since Hibar still didn't, please can you remove it for now till hiba add it

________________________________

In src/Components/Search/Search.js<https://github.com/Lebanon-WBC-Capstones/discover-the-north-web/pull/11#discussion_r574841112>:

> @@ -0,0 +1,56 @@
+import React, {useState} from  'react';
+import { SearchOutlined} from '@ant-design/icons';


same here for ant

________________________________

In package.json<https://github.com/Lebanon-WBC-Capstones/discover-the-north-web/pull/11#discussion_r574841447>:

> @@ -34,18 +36,5 @@
       "last 1 firefox version",
       "last 1 safari version"
     ]
-  },
-  "devDependencies": {


can I know why did you remove these?

________________________________

In package.json<https://github.com/Lebanon-WBC-Capstones/discover-the-north-web/pull/11#discussion_r574841635>:

>      "react": "^17.0.1",
     "react-dom": "^17.0.1",
-    "react-scripts": "4.0.1",
-    "web-vitals": "^0.2.4"
+    "react-scripts": "4.0.2",
+    "web-vitals": "^1.1.0"


why did you update this web-vitals version?

________________________________

In package.json<https://github.com/Lebanon-WBC-Capstones/discover-the-north-web/pull/11#discussion_r574842008>:

>    "version": "0.1.0",
   "private": true,
   "dependencies": {
-    "@testing-library/jest-dom": "^5.11.4",
-    "@testing-library/react": "^11.1.0",
-    "@testing-library/user-event": "^12.1.10",
+    "@ant-design/icons": "^4.5.0",


I like that you trying to implement this but this is @hiba28<https://github.com/hiba28> task for now

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/Lebanon-WBC-Capstones/discover-the-north-web/pull/11#pullrequestreview-589003600>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARSTVU4K3WVNIQWKLLBBL6LS6REPXANCNFSM4XPRN5KA>.

2021-02-12 21:29 UTC, osamaakb commented
Yes Maryam, you should commit all files that have changed but you shouldn't import ant since its not your tasks and that may cause problems for others, that's why I asked others to wait till Hiba import the css library, can you please do the requested changes ASAP

2021-02-12 22:38 UTC, closed without merging