Feat: add dropdown component
Lebanon-WBC-Capstones/discover-the-north-web pull request #19
Opened 2021-02-13 14:07 UTC by RaoufDannaoui1

we should add array of item to display them in the drop menu

2021-02-13 17:18 UTC, osamaakb reviewed
What will you do when the menu item is clicked?

2021-02-13 17:33 UTC, RaoufDannaoui1 commented
On click it will filter the activities for example and show only the ones that are in  this city

2021-02-13 17:49 UTC, osamaakb commented
> On click it will filter the activities for example and show only the ones that are in this city

Yes but I don't see the onClick function implemented, can you implement it please

2021-02-25 08:22 UTC, osamaakb requested changes

2021-02-25 08:22 UTC, osamaakb commented on src/Components/Dropdown/Dropdown.js
> +  activitiesArray,
why are you sending the activities here?

2021-02-25 08:22 UTC, osamaakb commented on src/Components/Dropdown/Dropdown.js
> +      if (act[elem] == value) {
this logic should be done in the page that's using the dropdown not here

2021-02-25 08:22 UTC, osamaakb commented on src/Components/Dropdown/Dropdown.js
> +  elem,
we don't need this one too

2021-02-27 16:03 UTC, osamaakb approved these changes

2021-02-27 16:03 UTC, merged