Feat: home page
Lebanon-WBC-Capstones/discover-the-north-web pull request #71
Opened 2021-02-24 22:23 UTC by bakhosRachwan

almost done still missing the what we do component and the header

2021-02-25 08:10 UTC, osamaakb commented
@bakhosRachwan please add them ASAP so we can merge this

2021-02-25 08:11 UTC, osamaakb requested changes

2021-02-25 08:11 UTC, osamaakb commented on src/Pages/HomePage/Homepage.js
> +  const guides = [
can you move this to a folder in the `src` name it `mockdata` and inside it add file called `data.js` and then export this array from there so we can keep it clean here

2021-02-27 16:43 UTC, osamaakb commented
@bakhosRachwan I merged the header, I think now you have everything to finish this page?

2021-02-28 10:24 UTC, bakhosRachwan commented
can we close and delete this branch and just merge the other one i pushed

2021-03-01 06:07 UTC, closed without merging